package p_04_25_random_generator;

import java.util.Scanner;

/**
 * A simple random generator obtained by the formula
 * <p><pre>
 * r_new = (a * r_old + b) % m</pre>
 * and then setting {@code r_old} to {@code r_new}. If {@code m} is chosen as
 * 2^32, then you can compute
 * <p><pre>
 * r_new = a * r_old + b</pre>
 * because the truncation of an overflowing result to the {@code int} type is
 * equivalent to computing the remainder. Write a program that asks the user
 * to enter a seed value for {@code r_old}. (Such a value is often called
 * seed). Then print the first 100 random integers generated by this formula,
 * using a = 32310901 and b = 1729.
 */
public class RandomGenerator
{
    public static void main(String[] args)
    {
        Scanner in = new Scanner(System.in);
        System.out.print("Enter seed value: ");
        int a = 32310901;
        int b = 1729;
        int m = (int) Math.pow(2, 32);

        do
        {
            int r_old = in.nextInt();

            for (int i = 0; i < 100; i++)
            {
                int r_new = (a * r_old + b) % m;
                r_old = r_new;
                System.out.printf("Random integers (%d): %d%n", i, r_new);
            }
            System.out.print("Enter seed value: ");
        } while (in.hasNextInt());
    }
}
